add_requires("freeglut", "stb", "miniaudio")
add_requires("emscripten 3.1.1", {alias = "emss"})
--add_requires("emscripten", {optional = true})
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})

target("aedes_attack")
    set_kind("binary")
    add_files("src/*.cpp")
    add_includedirs("include")
    set_targetdir("$(projectdir)/bin")
    add_packages("freeglut", "stb", "miniaudio")

target("wasm")
    set_default(false)
    set_plat("wasm")
    set_toolchains("emcc@emss")
    set_kind("binary")
    add_files("src/*.cpp")
    add_includedirs("include")
    set_policy("check.auto_ignore_flags", false)
    --add_packages("stb", "miniaudio")
    on_build(function (target)
        print(target:targetfile())
        os.exec("em++ -v")
       -- os.exec("em++ %s %s", "src/main.cpp", "src/*.cpp -O2 -Iinclude -sLEGACY_GL_EMULATION -sSTB_IMAGE -sWEBAUDIO_DEBUG -s USE_WEBGL2=1 --shell-file shell.html -sASSERTIONS -sALLOW_MEMORY_GROWTH -DMA_ENABLE_AUDIO_WORKLETS -sAUDIO_WORKLET=1 -sWASM_WORKERS=1 -sASYNCIFY -DMA_ENABLE_WEBAUDIO  --preload-file assets@../assets -DWEBGL_SIMPLE_ENABLE_EXTENSION=1")
    end)
    
-- 
   -- add_defines("MA_ENABLE_AUDIO_WORKLETS", "MA_ENABLE_WEBAUDIO", "WEBGL_SIMPLE_ENABLE_EXTENSION")
   -- add_cxxflags("-matomics -mbulk-memory -D__EMSCRIPTEN_SHARED_MEMORY__=1 -D__EMSCRIPTEN_WASM_WORKERS__=1");
   -- add_ldflags("-sLEGACY_GL_EMULATION",  "--shell-file shell.html", "--preload-file assets@../assets", "-sALLOW_MEMORY_GROWTH", "-sASYNCIFY", "-sAUDIO_WORKLET=1", "-sWASM_WORKERS=1")
   -- --add_ldflags(" -s USE_PTHREADS=1 -sWEBAUDIO_DEBUG -s USE_WEBGL2=1 -sASSERTIONS  -sASYNCIFY -DWEBGL_SIMPLE_ENABLE_EXTENSION=1")
   -- set_targetdir("$(projectdir)/bin")
   -- set_filename("aedes-attack.html")
   -- set_optimize("faster")
