name: Deploy to Cloudflare Pages

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deploy
    permissions:
      contents: read
      deployments: write
    container: emscripten/emsdk:3.1.61
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Emscripten
        run: emmake make

      - name: Copy & Move
        run: cp public/_headers build/_headers && mv build/aedes-attack.html build/index.html

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          projectName: aedes-attack
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'

