name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    container: emscripten/emsdk:3.1.61
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Emscripten
        run: emmake make

      - name: Copy
        run: cp public/_headers build/_headers

      - name: Print all environment variables
        run: env

      - name: Print secret environment variables
        run: env | grep SECRET

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: "sdasdasadsdasda"
          accountId: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: test
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'

